name: ci
on:
  # รันเมื่อมีการ push ไปยัง branch main
  push:
    branches:
      - main
  
  # รันเมื่อมีการ push ใด ๆ ภายใน Pull Request
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  run-ci-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Spin up containers
        run: make up
      - name: Run CI test
        run: make ci